### ISSUE TITLE
PostgreSQL error by creating database

### ISSUE THREAD

**Issue by Anaximelis** [equitania/odoo-addons#13]
While creating a new database on debain8 docker container i allways ran into an PostgreSQL error.

> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo-server/openerp/http.py", line 539, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 576, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 313, in _call_function
>     return self.endpoint(*args, **kwargs)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 805, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 405, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 703, in create
>     params['create_admin_pwd'])
>   File "/opt/odoo/odoo-server/openerp/http.py", line 881, in proxy_method
>     result = dispatch_rpc(self.service_name, method, args)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 115, in dispatch_rpc
>     result = dispatch(method, params)
>   File "/opt/odoo/odoo-server/openerp/service/db.py", line 73, in dispatch
>     return fn(*params)
>   File "/opt/odoo/odoo-server/openerp/service/db.py", line 90, in exp_create_database
>     _create_empty_database(db_name)
>   File "/opt/odoo/odoo-server/openerp/service/db.py", line 85, in _create_empty_database
>     cr.execute("""CREATE DATABASE "%s" ENCODING 'unicode' TEMPLATE "%s" """ % (name, chosen_template))
>   File "/opt/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
>     return f(self, *args, **kwargs)
>   File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
>     res = self._obj.execute(query, params)
> DataError: new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
> HINT:  Use the same encoding as in the template database, or use template0 as template.

The how-to from `https://gist.github.com/ffmike/877447` helps, but where ist the difference between template0 and template 1? Is there a way to init postgre with utf8 encoding?

**Comment by eqms** [comment]
Für Docker habe ich eigene Skripte erstellt. Werden in nächster Zeit auch veröffentlicht.
https://github.com/equitania/myodoo-docker - da ich inzwischen einen Release Manager für Odoo geschrieben habe, basiert der eigentliche Roleout darauf.
Odoo läuft auf jeden Fall derzeit nicht mit PostgreSQL 9.5, sondern nur bis 9.4
