### ISSUE TITLE
Produkt Suche eingrenzen auf Lieferanten beim Einkauf

### ISSUE THREAD

**Issue by wpichler** [equitania/odoo-addons#17]
Es wird da die name_search Methode erweitert - um vorher alle product_template_id's zu laden die zum Lieferanten gehören. Im nächsten Schritt werden aber dann diese template_ids in der Suche als product_id verwendet - und nicht als product_template_id - somit kommt es zu keinen oder falschen Ergebnissen.

Hier der Patch dafür:

diff --git a/equitania/product.py b/equitania/product.py
index 75853df..97f0243 100644
--- a/equitania/product.py
+++ b/equitania/product.py
@@ -45,7 +45,7 @@ class eq_product_product_new_api(models.Model):
             product_ids = [x[0] for x in supplierinfo]
             if args == None:
                 args = []
-            args.append(['id', 'in', product_ids])
+            args.append(['product_tmpl_id', 'in', product_ids])
         res = super(eq_product_product_new_api, self).name_search(name, args=args, operator=operator, limit=limit)
         return res

**Comment by eqms** [comment]
Danke - Wolfgang - haben wir übernommen.
