### ISSUE TITLE
eq_pos Boncode nicht lesbar

### ISSUE THREAD

**Issue by chris86tian** [equitania/odoo-addons#20]
Hallo Zusammen,

EAN Code ist 10-stellig / Angebot Ref. und mit Barcodescanner nicht lesbar.

![image](https://cloud.githubusercontent.com/assets/19744483/21425647/c0adae74-c84a-11e6-8adf-f1cd69b8c708.png)

Wie wird diese Nr. generiert?

Danke

Christian

**Comment by eqms** [comment]
Die Nummern-Generierung ist eine Basis-Möglichkeit von Odoo. 
Unter Einstellungen/Technisch...

**Comment by eqms** [comment]
https://equitania.atlassian.net/wiki/display/MW/MyOdoo+Wiki

**Comment by chris86tian** [comment]
Konnte leider im Buch und unter diesem Link etwas dazu finden.
Ich werde eine Anfrage über ihren Support machen.
