### ISSUE TITLE
Prepare Odoo Server Script killt SSH Systemlogin

### ISSUE THREAD

**Issue by SvenSFS** [equitania/odoo-addons#21]
Hallo,
habe gerade das Script prepare-odoo-server-debian8.sh einmal durchlaufen 
lassen und musste feststellen das es mein System, mehr oder weniger, zerschossen hat!

Das übel beginnt bei Zeile 177:
apt-get purge -y --auto-remove -o APT::AutoRemove::Recommend..........

Der Autoremove Prozess entfernt den SSH komplett, somit war das System dann 
von Extern TOT und nicht zu erreichen. Weitere Pakete werden auch entfernt:

altermime* bsd-mailx* clamav* clamdscan* fonts-droid* hicolor-icon-theme* irqbalance* libauthen-sasl-perl* libdrm-intel1* libdrm-nouveau2* libdrm-radeon1* libdrm2* libegl1-mesa* libegl1-mesa-drivers* libelf1* libgbm1* libgl1-mesa-dri* libgl1-mesa-glx* libglapi-mesa*
  libgstreamer-plugins-base0.10-0* libgstreamer0.10-0* libgtk2.0-bin* liblockfile1* libmtdev1* libnuma1* libopenvg1-mesa* liborc-0.4-0* libpaper-utils* libpciaccess0* libqt5core5a* libqt5dbus5* libqt5gui5* libqt5network5* libqt5opengl5* libqt5printsupport5* libqt5qml5*
  libqt5quick5* libqt5sql5* libqt5sql5-sqlite* libqt5svg5* libqt5webkit5* libqt5widgets5* libqt5xmlpatterns5* libsasl2-modules* libtxc-dxtn-s2tc0* libwayland-client0* libwayland-egl1-mesa* libwayland-server0* libx11-xcb1* libxcb-dri2-0* libxcb-dri3-0* libxcb-glx0*
  libxcb-icccm4* libxcb-image0* libxcb-keysyms1* libxcb-present0* libxcb-randr0* libxcb-render-util0* libxcb-shape0* libxcb-sync1* libxcb-util0* libxcb-xfixes0* libxcb-xkb1* libxkbcommon-x11-0* libxkbcommon0* libxkbfile1* libxmuu1* libxshmfence1* libxxf86vm1* ndiff*
  openssh-server* openssh-sftp-server* php5-readline* python-dnspython* python-pyicu* qttranslations5-l10n* ripole* util-linux-locales* whois* x11-xkb-utils* xauth* xnest* xserver-common*

Sven

**Comment by chris86tian** [comment]
Hallo Sven,

man sollte vielleicht das Script anpassen und wichtige Tools als manual markieren:
`
&& apt-mark manual openssh-server openssh-sftp-server;
`
Kannst du die Zeile mal 2 Zeilen vorher einfügen und testen, dann könnte man es in den Code aufnehmen!

Danke
Christian

**Comment by eqms** [comment]
Das Skript wurde jetzt mehrere 100 Mal eingesetzt. 
apt-get autoremove entfernt nur, was vorher als veraltet, überflüssig oder manuell mit apt-get purge markiert wurde.

Die Ursache liegt an der Grundinstallation und nicht am Skript.

**Comment by SvenSFS** [comment]
werde ich mal testen.
das system auf den ich das getestet habe ist nen system von hetzner mit minimaler
installation.

**Comment by eqms** [comment]
Genau den selben Server setze ich auch ein allerdings auf Basis von Docker.
In Kürze (Ende Dezember) gibt es ein Buch Update das die Einrichtung auf Basis von Docker zeigt.
